#auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “Dian's Blog”
title: Dian's blog
description: Everything about Dian.
url: http://blog.bithinker.com
feed: /atom.xml
author_info: <a href="http://blog.bithinker.com/">Dian</a>
